#!/bin/sh

bat="/sys/class/power_supply/BAT1"

cap=$(cat "$bat/capacity")
stat=$(cat "$bat/status")

case "$stat" in
    Charging|Full) printf "%s%%*\n" "$cap" ;;
    "Not charging") printf "%s%%!\n" "$cap" ;;
    Discharging) printf "%s%%\n" "$cap" ;;
    *) printf "%s%%E\n" "$cap" ;;
esac
