#!/bin/sh

net=$(ip link show | awk '/state UP/ {print $2}' | sed 's/://')
ssid=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2)

ip=$(ip -4 addr show "$net" 2>/dev/null | awk '/inet / {print $2}' | cut -d/ -f1)

printf "%s %s" "${ssid:-NoNet}" "$ip"
