#!/bin/sh

vol=$(pamixer --get-volume)%$(pamixer --get-mute | grep -q true && echo " [MUTE]" || echo "")
mic=$(pactl get-source-mute @DEFAULT_SOURCE@ | grep -q yes && echo "" || echo "*")

printf "%s%s" "$mic" "$vol"
